Fix the NotImplementedError when calculate diff/pp for unsupported game modes
zcWSR/japari-admin pull request #12
Opened 2021-01-06 07:18 UTC by kami-poi

2021-01-06 19:28 UTC, zcWSR commented on src/services/osu-service.js
> +      }
getPP 的调用方有个如果为 string 类型返回值就直接输出的逻辑 👇
https://github.com/zcWSR/japari-admin/blob/ab8847b06b226cda1f619b28a4d967368dda2cda/src/services/osu-service.js#L266-L272

所以这里其实可以改成返回 string，并且如果判断不出错误可以考虑继续向上抛，顶层 koa 有个 middleware 会拦截住异常

2021-01-06 19:29 UTC, zcWSR commented on src/services/osu-service.js
> +      }
修改建议
```suggestion
        if (e.name === "NotImplementedError") {
            return 'mode 不支持';
        }
        new Error('未知错误');
      }
```

2021-01-06 19:36 UTC, zcWSR commented on src/services/osu-service.js
> +        const stars = new OSU.diff().calc({
改一下缩进，用 2 缩进

2021-01-06 19:38 UTC, zcWSR requested changes
两个小地方

2021-01-07 05:48 UTC, kami-poi reviewed
按照要求修改了代码

2021-01-07 05:48 UTC, kami-poi commented on src/services/osu-service.js
> +      }
这里意图是在遇到不支持的模式时，也能够正常输出大部分数据。所以返回一个人为指定的对象。
```suggestion
        if (e.name === "NotImplementedError")
            return {
                acc: 0,
                pp: "N/A",
                map
            };
            throw e;
      }
```

2021-01-07 05:48 UTC, kami-poi commented on src/services/osu-service.js
> +        const stars = new OSU.diff().calc({
已修改

2021-01-07 11:13 UTC, zcWSR approved these changes
done

2021-01-07 11:13 UTC, merged